#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

readonly base_config="${KAFKA_HOME}/config/connect-distributed.properties"
readonly worker_config="${CONNECT_CONFIG_FILE:-/tmp/connect-distributed.properties}"

cp "$base_config" "$worker_config"

while IFS='=' read -r name value; do
  case "$name" in
    CONNECT_CONFIG_FILE)
      ;;
    CONNECT_*)
      property="${name#CONNECT_}"
      property="${property,,}"
      property="${property//_/.}"
      printf '%s=%s\n' "$property" "$value" >> "$worker_config"
      ;;
  esac
done < <(env | sort)

exec "${KAFKA_HOME}/bin/connect-distributed.sh" "$worker_config"
